base:
  random_state: 42

data:
  dataset_csv: 'data/raw/raw.csv'
  features_path: 'data/interim/featured_raw.csv'
  test_size: 0.2
  trainset_path: 'data/processed/train.csv'
  testset_path: 'data/processed/test.csv'